version: "3.9"

services:
  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  mongodb:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - 27017:27017

volumes:
  cache:
    driver: local
